version: '3.8'

services:
  core:
    build: ./drivelink-core
    depends_on:
      - postgres
    ports:
      - '8080:8080'
    environment:
      POSTGRES_JDBC_USER: myuser
      POSTGRES_JDBC_PASS: secret
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/mydatabase"

  postgres:
    image: 'postgres:16-alpine'
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
  
  webapp:
    build: ./drivelink-webapp
    depends_on:
      - core
    ports:
      - 80:80

volumes:
  postgres:
  